version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 644370125687.dkr.ecr.ca-central-1.amazonaws.com
      - REPO_URI=644370125687.dkr.ecr.ca-central-1.amazonaws.com/eks-multi-az-node-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Writing image details to imageDetail.json...
      - printf '[{"name":"node-app","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
